package io.github.fludakit.examples.vanilla;

import io.github.fludakit.jdbc.JdbcClient;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class VanillaExampleTest {

    private JdbcClient client;

    @BeforeEach
    void setUp() throws Exception {
        var ds = Utils.newDataSource();
        client = new JdbcClient(ds);
        try (var conn = ds.getConnection(); var stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS engineers");
            stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
        }
    }

    @Test
    void crud() {
        // insert
        assertEquals(1, client.sql("INSERT INTO engineers (name) VALUES (:name)").param("name", "Ada").update());

        // get all
        List<Engineer> all = client.sql("SELECT id, name FROM engineers ORDER BY id").query(Engineer.class).list();
        assertEquals(1, all.size());
        assertEquals("Ada", all.get(0).name());

        // get by id
        Engineer ada = client.sql("SELECT id, name FROM engineers WHERE id = :id")
                .param("id", all.get(0).id()).query(Engineer.class).single();
        assertEquals("Ada", ada.name());

        // update
        client.sql("UPDATE engineers SET name = :name WHERE id = :id")
                .param("name", "Ada Lovelace").param("id", ada.id()).update();
        Engineer updated = client.sql("SELECT id, name FROM engineers WHERE id = :id")
                .param("id", ada.id()).query(Engineer.class).single();
        assertEquals("Ada Lovelace", updated.name());

        // delete
        client.sql("DELETE FROM engineers WHERE id = :id").param("id", ada.id()).update();
        assertTrue(client.sql("SELECT id, name FROM engineers").query(Engineer.class).list().isEmpty());
    }
}
