<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.hantsy.jdbc</groupId>
        <artifactId>jdbc-client-examples</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>jdbc-client-example-javase</artifactId>
    <packaging>jar</packaging>

    <name>jdbc-client-example-javase</name>
    <description>Java SE example bootstrapping CDI with Weld SE and using the injected JdbcClient.</description>

    <dependencies>
        <dependency>
            <groupId>io.github.hantsy.jdbc</groupId>
            <artifactId>jdbc-client-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.hantsy.jdbc</groupId>
            <artifactId>jdbc-client-cdi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.weld.se</groupId>
            <artifactId>weld-se-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.weld</groupId>
            <artifactId>weld-junit5</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
