package io.github.hantsy.jdbc.examples.servlet;

import io.github.hantsy.jdbc.JdbcClient;
import io.github.hantsy.jdbc.support.GeneratedKeyHolder;
import io.github.hantsy.jdbc.support.KeyHolder;

import jakarta.annotation.Resource;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import javax.sql.DataSource;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;

/**
 * A minimal CRUD servlet backed by the core {@link JdbcClient}. The {@link DataSource} is provided by
 * the container through JNDI ({@code META-INF/context.xml}) and injected with {@code @Resource}.
 *
 * <p>Endpoints: {@code GET /engineers}, {@code GET /engineers/{id}}, {@code POST /engineers?name=...},
 * {@code PUT /engineers/{id}?name=...}, {@code DELETE /engineers/{id}}.</p>
 */
@WebServlet("/engineers/*")
public class EngineerServlet extends HttpServlet {

    @Resource(name = "jdbc/myDS")
    private DataSource dataSource;

    private JdbcClient client;

    @Override
    public void init() throws ServletException {
        try (var conn = dataSource.getConnection(); var stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS engineers ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
        } catch (SQLException e) {
            throw new ServletException("Failed to initialize the engineers table", e);
        }
        this.client = new JdbcClient(dataSource);
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        resp.setContentType("text/plain;charset=UTF-8");
        String id = idFromPath(req);
        if (id == null) {
            List<Engineer> all = client.sql("SELECT id, name FROM engineers ORDER BY id")
                    .query(Engineer.class).list();
            resp.getWriter().println(all);
        } else {
            Engineer engineer = client.sql("SELECT id, name FROM engineers WHERE id = :id")
                    .param("id", Long.parseLong(id)).query(Engineer.class).single();
            resp.getWriter().println(engineer);
        }
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        String name = req.getParameter("name");
        KeyHolder holder = new GeneratedKeyHolder();
        client.sql("INSERT INTO engineers (name) VALUES (:name)").param("name", name).update(holder);
        resp.setStatus(HttpServletResponse.SC_CREATED);
        resp.getWriter().println("created id=" + ((Number) holder.getKey()).longValue());
    }

    @Override
    protected void doPut(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        String id = idFromPath(req);
        String name = req.getParameter("name");
        client.sql("UPDATE engineers SET name = :name WHERE id = :id")
                .param("name", name).param("id", Long.parseLong(id)).update();
        resp.getWriter().println("updated id=" + id);
    }

    @Override
    protected void doDelete(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        String id = idFromPath(req);
        client.sql("DELETE FROM engineers WHERE id = :id").param("id", Long.parseLong(id)).update();
        resp.getWriter().println("deleted id=" + id);
    }

    private String idFromPath(HttpServletRequest req) {
        String path = req.getPathInfo();
        if (path == null || path.equals("/") || path.isBlank()) {
            return null;
        }
        return path.substring(1);
    }
}
