package io.github.fludakit.examples.vanilla;

import io.github.fludakit.jdbc.JdbcClient;
import io.github.fludakit.jdbc.support.GeneratedKeyHolder;
import io.github.fludakit.jdbc.support.KeyHolder;

import java.util.List;

/**
 * Plain {@link JdbcClient} usage against an in-memory H2 DataSource, with no CDI at all.
 *
 * <p>Run with {@code mvn -f examples/pom.xml -pl vanilla exec:java -Dexec.mainClass=...} or from an IDE.</p>
 */
public class VanillaExample {

    public static void main(String[] args) throws Exception {
        var ds = Utils.newDataSource();

        JdbcClient client = new JdbcClient(ds);
        try (var conn = ds.getConnection(); var stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
        }

        // insert
        KeyHolder holder = new GeneratedKeyHolder();
        client.sql("INSERT INTO engineers (name) VALUES (:name)").param("name", "Ada").update(holder);
        long adaId = ((Number) holder.getKey()).longValue();
        client.sql("INSERT INTO engineers (name) VALUES (:name)").param("name", "Grace").update();

        // get all
        List<Engineer> all = client.sql("SELECT id, name FROM engineers ORDER BY id").query(Engineer.class).list();
        System.out.println("all = " + all);

        // get by id
        Engineer ada = client.sql("SELECT id, name FROM engineers WHERE id = :id")
                .param("id", adaId).query(Engineer.class).single();
        System.out.println("byId = " + ada);

        // update
        client.sql("UPDATE engineers SET name = :name WHERE id = :id")
                .param("name", "Ada Lovelace").param("id", adaId).update();

        // delete
        client.sql("DELETE FROM engineers WHERE id = :id").param("id", adaId).update();

        System.out.println("remaining = "
                + client.sql("SELECT id, name FROM engineers ORDER BY id").query(Engineer.class).list());
    }
}
