package io.github.hantsy.jdbc;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit5.container.annotation.ArquillianTest;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.EmptyAsset;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.jboss.shrinkwrap.resolver.api.maven.Maven;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import javax.sql.DataSource;
import jakarta.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Exercises the JTA-transactional {@link EngineerService} by injecting it directly and driving it
 * against the container-managed XA {@link DataSource}.
 */
@ArquillianTest
public class EngineerServiceIT {

    @Inject
    EngineerService service;

    @Inject
    DataSource dataSource;

    @Deployment
    public static WebArchive createDeployment() {
        var libs = Maven.resolver().loadPomFromFile("pom.xml")
                .resolve("org.postgresql:postgresql")
                .withTransitivity()
                .asFile();
        return ShrinkWrap.create(WebArchive.class, "engineer-service.war")
                .addAsLibraries(libs)
                .addPackages(true, "io.github.hantsy.jdbc")
                .addAsResource("microprofile-config.properties")
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
    }

    @BeforeEach
    void setUp() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS engineers");
            stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dev_name VARCHAR(255))");
            stmt.execute("INSERT INTO engineers (dev_name) VALUES ('Duke Jakarta')");
            stmt.execute("INSERT INTO engineers (dev_name) VALUES ('Arquillian Glassfish')");
        }
    }

    @Test
    void findAllReturnsAllRows() {
        List<Engineer> all = service.findAll();
        assertEquals(2, all.size());
        assertEquals("Duke Jakarta", all.get(0).devName());
        assertEquals("Arquillian Glassfish", all.get(1).devName());
    }

    @Test
    void findByIdReturnsSingleRow() {
        Engineer duke = service.findById(1L);
        assertEquals("Duke Jakarta", duke.devName());
    }

    @Test
    void createReturnsGeneratedId() {
        Engineer created = service.create(new Engineer(null, "New Dev"));
        assertNotNull(created.id());
        assertEquals("New Dev", created.devName());
        assertEquals(3, service.findAll().size());
    }

    @Test
    void updateChangesName() {
        service.update(1L, new Engineer(null, "Updated Duke"));
        assertEquals("Updated Duke", service.findById(1L).devName());
    }

    @Test
    void deleteRemovesRow() {
        service.delete(1L);
        List<Engineer> remaining = service.findAll();
        assertEquals(1, remaining.size());
        assertEquals("Arquillian Glassfish", remaining.get(0).devName());
    }
}
