package io.github.hantsy.jdbc;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit5.container.annotation.ArquillianTest;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.EmptyAsset;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.jboss.shrinkwrap.resolver.api.maven.Maven;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.net.URL;
import java.sql.Connection;
import java.sql.Statement;
import javax.sql.DataSource;
import jakarta.inject.Inject;
import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.client.WebTarget;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises the JAX-RS {@link EngineerResource} over HTTP with the Jakarta REST client, against the
 * container-managed XA {@link DataSource}.
 */
@ArquillianTest
public class JakartaEEExampleIT {

    @ArquillianResource
    URL baseUrl;

    @Inject
    DataSource dataSource;

    @Deployment
    public static WebArchive createDeployment() {
        var libs = Maven.resolver().loadPomFromFile("pom.xml")
                .resolve("org.postgresql:postgresql")
                .withTransitivity()
                .asFile();
        return ShrinkWrap.create(WebArchive.class, "jakartaee-example.war")
                .addAsLibraries(libs)
                .addPackages(true, "io.github.hantsy.jdbc")
                .addAsResource("microprofile-config.properties")
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
    }

    @BeforeEach
    void setUp() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS engineers");
            stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dev_name VARCHAR(255))");
            stmt.execute("INSERT INTO engineers (dev_name) VALUES ('Duke Jakarta')");
        }
    }

    @Test
    void crudOverHttp() {
        try (Client client = ClientBuilder.newClient()) {
            WebTarget target = client.target(baseUrl.toExternalForm()).path("api/engineers");

            // create
            try (Response created = target.request(MediaType.APPLICATION_JSON)
                    .post(Entity.entity("{\"devName\":\"Ada Lovelace\"}", MediaType.APPLICATION_JSON))) {
                assertEquals(Response.Status.CREATED.getStatusCode(), created.getStatus());
                assertTrue(created.readEntity(String.class).contains("Ada Lovelace"));
            }

            // get all
            try (Response all = target.request(MediaType.APPLICATION_JSON).get()) {
                assertEquals(200, all.getStatus());
                String body = all.readEntity(String.class);
                assertTrue(body.contains("Duke Jakarta"), body);
                assertTrue(body.contains("Ada Lovelace"), body);
            }

            // get by id
            try (Response byId = target.path("1").request(MediaType.APPLICATION_JSON).get()) {
                assertEquals(200, byId.getStatus());
                assertTrue(byId.readEntity(String.class).contains("Duke Jakarta"));
            }

            // update
            try (Response updated = target.path("1").request()
                    .put(Entity.entity("{\"devName\":\"Updated Duke\"}", MediaType.APPLICATION_JSON))) {
                assertEquals(Response.Status.NO_CONTENT.getStatusCode(), updated.getStatus());
            }

            // verify the update
            try (Response byId = target.path("1").request(MediaType.APPLICATION_JSON).get()) {
                assertTrue(byId.readEntity(String.class).contains("Updated Duke"));
            }

            // delete
            try (Response deleted = target.path("1").request().delete()) {
                assertEquals(Response.Status.NO_CONTENT.getStatusCode(), deleted.getStatus());
            }
        }
    }
}
