package io.github.hantsy.jdbc.examples.javase;

import io.github.hantsy.jdbc.cdi.ConverterRegistryProducer;
import io.github.hantsy.jdbc.cdi.JdbcClientProducer;
import io.github.hantsy.jdbc.tx.cdi.TransactionalCdiExtension;
import io.github.hantsy.jdbc.tx.cdi.TransactionalInterceptor;
import org.jboss.weld.junit5.WeldInitiator;
import org.jboss.weld.junit5.WeldJunit5Extension;
import org.jboss.weld.junit5.WeldSetup;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.List;
import javax.sql.DataSource;
import jakarta.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises the transactional {@link EngineerService} with Weld SE, mirroring the {@code tx}
 * module's own integration-test wiring.
 */
@ExtendWith(WeldJunit5Extension.class)
class JavaSeExampleTest {

    @WeldSetup
    public WeldInitiator weld = WeldInitiator.from(
            JdbcClientProducer.class,
            ConverterRegistryProducer.class,
            DataSourceProducer.class,
            EngineerService.class,
            TransactionalInterceptor.class,
            TransactionalCdiExtension.class
    ).build();

    @Inject
    EngineerService service;

    @Inject
    DataSource dataSource;

    @BeforeEach
    void setUp() throws Exception {
        try (var conn = dataSource.getConnection(); var stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS engineers");
            stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
        }
    }

    @Test
    void crud() {
        long id = service.create("Ada");

        List<Engineer> all = service.findAll();
        assertEquals(1, all.size());
        assertEquals("Ada", all.get(0).name());

        Engineer ada = service.findById(id);
        assertEquals("Ada", ada.name());

        service.update(id, "Ada Lovelace");
        assertEquals("Ada Lovelace", service.findById(id).name());

        service.delete(id);
        assertTrue(service.findAll().isEmpty());
    }

    @Test
    void rollsBackOnRuntimeException() {
        assertThrows(IllegalStateException.class, () -> service.createTwo("Ada", ""));
        assertTrue(service.findAll().isEmpty());
    }
}
