package io.github.hantsy.jdbc.examples.javase;

import io.github.hantsy.jdbc.JdbcClient;
import io.github.hantsy.jdbc.cdi.ConverterRegistryProducer;
import io.github.hantsy.jdbc.cdi.JdbcClientProducer;
import org.jboss.weld.junit5.auto.AddBeanClasses;
import org.jboss.weld.junit5.auto.EnableAutoWeld;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import jakarta.inject.Inject;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises the CDI-produced {@link JdbcClient} with Weld's JUnit 5 extension, mirroring the
 * {@code cdi} module's own tests.
 */
@EnableAutoWeld
@AddBeanClasses({JdbcClientProducer.class, ConverterRegistryProducer.class, DataSourceProducer.class})
class JavaSeExampleTest {

    @Inject
    JdbcClient client;

    @Inject
    DataSource dataSource;

    @BeforeEach
    void setUp() throws Exception {
        try (var conn = dataSource.getConnection(); var stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS engineers");
            stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
        }
    }

    @Test
    void crud() {
        // insert
        assertEquals(1, client.sql("INSERT INTO engineers (name) VALUES (:name)").param("name", "Ada").update());

        // get all
        List<Engineer> all = client.sql("SELECT id, name FROM engineers ORDER BY id").query(Engineer.class).list();
        assertEquals(1, all.size());
        assertEquals("Ada", all.get(0).name());

        // get by id
        Engineer ada = client.sql("SELECT id, name FROM engineers WHERE id = :id")
                .param("id", all.get(0).id()).query(Engineer.class).single();
        assertEquals("Ada", ada.name());

        // update
        client.sql("UPDATE engineers SET name = :name WHERE id = :id")
                .param("name", "Ada Lovelace").param("id", ada.id()).update();
        Engineer updated = client.sql("SELECT id, name FROM engineers WHERE id = :id")
                .param("id", ada.id()).query(Engineer.class).single();
        assertEquals("Ada Lovelace", updated.name());

        // delete
        client.sql("DELETE FROM engineers WHERE id = :id").param("id", ada.id()).update();
        assertTrue(client.sql("SELECT id, name FROM engineers").query(Engineer.class).list().isEmpty());
    }
}
