package io.github.hantsy.jdbc.examples.javase;

import org.jboss.weld.environment.se.Weld;
import org.jboss.weld.environment.se.WeldContainer;

import javax.sql.DataSource;

/**
 * Bootstraps CDI with Weld SE, creates the demo table, then exercises the transactional
 * {@link EngineerService}.
 */
public class Main {

    public static void main(String[] args) throws Exception {
        try (WeldContainer container = new Weld().initialize()) {
            DataSource dataSource = container.select(DataSource.class).get();
            try (var conn = dataSource.getConnection(); var stmt = conn.createStatement()) {
                stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
            }

            EngineerService service = container.select(EngineerService.class).get();

            // insert
            long adaId = service.create("Ada");
            service.create("Grace");

            // get all
            System.out.println("all = " + service.findAll());

            // get by id
            System.out.println("byId = " + service.findById(adaId));

            // update
            service.update(adaId, "Ada Lovelace");

            // delete
            service.delete(adaId);

            System.out.println("remaining = " + service.findAll());
        }
    }
}
