package io.github.hantsy.jdbc.examples.javase;

import io.github.hantsy.jdbc.JdbcClient;
import io.github.hantsy.jdbc.support.GeneratedKeyHolder;
import io.github.hantsy.jdbc.support.KeyHolder;
import org.jboss.weld.environment.se.Weld;
import org.jboss.weld.environment.se.WeldContainer;

import javax.sql.DataSource;
import java.util.List;

/**
 * Bootstraps CDI with Weld SE, then uses the CDI-produced {@link JdbcClient} for a small CRUD demo.
 */
public class Main {

    public static void main(String[] args) throws Exception {
        try (WeldContainer container = new Weld().initialize()) {
            DataSource dataSource = container.select(DataSource.class).get();
            try (var conn = dataSource.getConnection(); var stmt = conn.createStatement()) {
                stmt.execute("CREATE TABLE engineers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
            }

            JdbcClient client = container.select(JdbcClient.class).get();

            // insert
            KeyHolder holder = new GeneratedKeyHolder();
            client.sql("INSERT INTO engineers (name) VALUES (:name)").param("name", "Ada").update(holder);
            long adaId = ((Number) holder.getKey()).longValue();
            client.sql("INSERT INTO engineers (name) VALUES (:name)").param("name", "Grace").update();

            // get all
            List<Engineer> all = client.sql("SELECT id, name FROM engineers ORDER BY id").query(Engineer.class).list();
            System.out.println("all = " + all);

            // get by id
            Engineer ada = client.sql("SELECT id, name FROM engineers WHERE id = :id")
                    .param("id", adaId).query(Engineer.class).single();
            System.out.println("byId = " + ada);

            // update
            client.sql("UPDATE engineers SET name = :name WHERE id = :id")
                    .param("name", "Ada Lovelace").param("id", adaId).update();

            // delete
            client.sql("DELETE FROM engineers WHERE id = :id").param("id", adaId).update();

            System.out.println("remaining = "
                    + client.sql("SELECT id, name FROM engineers ORDER BY id").query(Engineer.class).list());
        }
    }
}
