package io.github.hantsy.jdbc;

import io.github.hantsy.jdbc.support.GeneratedKeyHolder;
import io.github.hantsy.jdbc.support.KeyHolder;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit5.container.annotation.ArquillianTest;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.EmptyAsset;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.jboss.shrinkwrap.resolver.api.maven.Maven;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;
import jakarta.inject.Inject;

@ArquillianTest
public class JdbcClientIT {
    private static final Logger LOGGER = Logger.getLogger(JdbcClientIT.class.getName());
    @Inject
    private JdbcClient jdbcClient;
    @Inject
    private DataSource dataSource;

    @Deployment
    public static WebArchive createDeployment() {
        var libs = Maven.resolver().loadPomFromFile("pom.xml")
                .resolve("org.postgresql:postgresql")
                .withTransitivity()
                .asFile();
        WebArchive archive = ShrinkWrap.create(WebArchive.class, "test-jdbc-client.war")
                .addAsLibraries(libs)
                .addPackages(true, "io.github.hantsy.jdbc")
                .addAsResource("microprofile-config.properties")
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
        LOGGER.log(Level.INFO, "deployment archive: {0}", archive.toString(true));
        return archive;
    }

    @BeforeEach
    public void setupDatabase() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS engineers");
            stmt.execute("CREATE TABLE engineers (id BIGINT PRIMARY KEY, dev_name VARCHAR(255))");
            stmt.execute("INSERT INTO engineers VALUES (1, 'Duke Jakarta')");
            stmt.execute("INSERT INTO engineers VALUES (2, 'Arquillian Glassfish')");

            stmt.execute("DROP TABLE IF EXISTS engineers_gen");
            stmt.execute("CREATE TABLE engineers_gen (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dev_name VARCHAR(255))");
        }
    }

    @Test
    public void verifyNamedAndPositionalQueryProjections() {
        List<DevSummary> namedResult = jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = :targetId")
                .param("targetId", 1L)
                .query(DevSummary.class)
                .list();
        Assertions.assertEquals(1, namedResult.size());
        Assertions.assertEquals("Duke Jakarta", namedResult.get(0).devName());

        List<DevSummary> positionalResult = jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = ?")
                .param(2L)
                .query(DevSummary.class)
                .list();
        Assertions.assertEquals(1, positionalResult.size());
        Assertions.assertEquals("Arquillian Glassfish", positionalResult.get(0).devName());
    }

    @Test
    public void singleReturnsExactlyOneRow() {
        DevSummary result = jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = :id")
                .param("id", 1L)
                .query(DevSummary.class)
                .single();
        Assertions.assertEquals("Duke Jakarta", result.devName());
    }

    @Test
    public void singleThrowsWhenEmpty() {
        Assertions.assertThrows(JdbcClientException.class, () ->
                jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = :id")
                        .param("id", 999L)
                        .query(DevSummary.class)
                        .single());
    }

    @Test
    public void singleThrowsWhenMultipleRows() {
        Assertions.assertThrows(JdbcClientException.class, () ->
                jdbcClient.sql("SELECT id, dev_name FROM engineers")
                        .query(DevSummary.class)
                        .single());
    }

    @Test
    public void optionalReturnsValueWhenFound() {
        Optional<DevSummary> result = jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = :id")
                .param("id", 1L)
                .query(DevSummary.class)
                .optional();
        Assertions.assertTrue(result.isPresent());
        Assertions.assertEquals("Duke Jakarta", result.get().devName());
    }

    @Test
    public void optionalIsEmptyWhenNotFound() {
        Optional<DevSummary> result = jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = :id")
                .param("id", 999L)
                .query(DevSummary.class)
                .optional();
        Assertions.assertTrue(result.isEmpty());
    }

    @Test
    public void optionalThrowsWhenMultipleRows() {
        Assertions.assertThrows(JdbcClientException.class, () ->
                jdbcClient.sql("SELECT id, dev_name FROM engineers")
                        .query(DevSummary.class)
                        .optional());
    }

    @Test
    public void singleValueReadsScalar() {
        Long count = jdbcClient.sql("SELECT COUNT(*) FROM engineers")
                .singleValue(Long.class);
        Assertions.assertEquals(2L, count);
    }

    @Test
    public void singleValueThrowsWhenEmpty() {
        Assertions.assertThrows(JdbcClientException.class, () ->
                jdbcClient.sql("SELECT id FROM engineers WHERE id = 999").singleValue(Long.class));
    }

    @Test
    public void optionalValueReadsScalar() {
        Optional<Long> count = jdbcClient.sql("SELECT COUNT(*) FROM engineers")
                .optionalValue(Long.class);
        Assertions.assertEquals(Optional.of(2L), count);
    }

    @Test
    public void queryWithCustomRowMapper() {
        List<String> names = jdbcClient.sql("SELECT dev_name FROM engineers ORDER BY id")
                .query((rs, rowNum) -> rs.getString("dev_name"))
                .list();
        Assertions.assertEquals(List.of("Duke Jakarta", "Arquillian Glassfish"), names);
    }

    @Test
    public void streamYieldsAllRows() {
        List<DevSummary> all = jdbcClient.sql("SELECT id, dev_name FROM engineers ORDER BY id")
                .query(DevSummary.class)
                .stream()
                .toList();
        Assertions.assertEquals(2, all.size());
        Assertions.assertEquals("Duke Jakarta", all.get(0).devName());
    }

    @Test
    public void paramsWithMap() {
        List<DevSummary> result = jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = :id")
                .params(Map.of("id", 1L))
                .query(DevSummary.class)
                .list();
        Assertions.assertEquals("Duke Jakarta", result.get(0).devName());
    }

    @Test
    public void paramsWithVarargs() {
        List<DevSummary> result = jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = ?")
                .params(2L)
                .query(DevSummary.class)
                .list();
        Assertions.assertEquals("Arquillian Glassfish", result.get(0).devName());
    }

    @Test
    public void updateWithKeyHolderPopulatesHolder() {
        KeyHolder holder = new GeneratedKeyHolder();
        int rows = jdbcClient.sql("INSERT INTO engineers_gen (dev_name) VALUES (:name)")
                .param("name", "Another Dev")
                .update(holder);
        Assertions.assertEquals(1, rows);
        Assertions.assertNotNull(holder.getKey());
    }

    @Test
    public void batchUpdateWithNamedMaps() {
        List<Map<String, Object>> batch = List.of(
                Map.of("name", "Dev C"),
                Map.of("name", "Dev D"));
        int[] counts = jdbcClient.sql("INSERT INTO engineers_gen (dev_name) VALUES (:name)")
                .batchUpdate(batch);
        Assertions.assertEquals(2, counts.length);
    }

    @Test
    public void batchUpdateWithPositionalArrays() {
        Object[][] batch = {{"Dev E"}, {"Dev F"}};
        int[] counts = jdbcClient.sql("INSERT INTO engineers_gen (dev_name) VALUES (?)")
                .batchUpdate(batch);
        Assertions.assertEquals(2, counts.length);
    }

    @Test
    public void queryTimeoutIsAccepted() {
        List<DevSummary> all = jdbcClient.sql("SELECT id, dev_name FROM engineers ORDER BY id")
                .queryTimeout(10)
                .query(DevSummary.class)
                .list();
        Assertions.assertEquals(2, all.size());
    }

    @Test
    public void fetchSizeIsAccepted() {
        List<DevSummary> result = jdbcClient.sql("SELECT id, dev_name FROM engineers ORDER BY id")
                .fetchSize(10)
                .query(DevSummary.class)
                .list();
        Assertions.assertEquals(2, result.size());
    }

    @Test
    public void mixingNamedAndPositionalThrows() {
        Assertions.assertThrows(IllegalArgumentException.class, () ->
                jdbcClient.sql("SELECT id, dev_name FROM engineers WHERE id = :id")
                        .param("id", 1L)
                        .param(1L));
    }

    @Test
    public void dataSourceInjectionSelectOne() throws Exception {
        Assertions.assertNotNull(dataSource);
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT 1")) {
            Assertions.assertTrue(rs.next());
            Assertions.assertEquals(1, rs.getInt(1));
        }
    }

    @Test
    public void jdbcClientInjectionSelectOne() {
        Assertions.assertNotNull(jdbcClient);
        int one = jdbcClient.sql("SELECT 1").singleValue(Integer.class);
        Assertions.assertEquals(1, one);
    }
}
