name: gh-pages

on:
  push:
    paths:
      - "docs/**"
      - "pom.xml"
      - ".github/workflows/docs.yml"
      - "mkdocs.yml"
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build MkDocs site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: docs/requirements.txt

      - name: Install MKDocs dependencies
        run: python -m pip install -r docs/requirements.txt

      - run: mkdocs gh-deploy --force
